### PR TITLE
added navbar

### PR DESCRIPTION
**Pull request by Tess-Vanta**
Frontend changes in react js

### CODE REVIEW

**Comment by opticSquid** [comment]
Hey tests are failing.... You are using `react-router-dom` but `package.json` under website folder doesn't mention it... See this and please fix it

**Comment by opticSquid** [comment]
Hey tests are failing.... You are using `react-router-dom` but `package.json` under website folder doesn't mention it... See this and please fix it

**Comment by Tess-Vanta** [comment]
> Hey tests are failing.... You are using `react-router-dom` but `package.json` under website folder doesn't mention it... See this and please fix it

okay, ill see to that

**Comment by opticSquid** [comment]
Closing this pr because you have made another one which contains these changes and the tests here are also failing...

**Review by opticSquid — COMMENTED** [review]
fix the code fro the errors mentioned in the comment

**Pull request closed without merging**
