### PR TITLE
Added figma UI designs

### PR DESCRIPTION
**Pull request by DarkFalc0n**
#15 Figma designs have been embedded into the readme. Also, the UI renderings have been included under Assets/Mobile Designs/

### CODE REVIEW

**Comment by opticSquid** [comment]
Hey there is a problem in the workflows given in the event so where the PRs raised from forks are getting errored out because of some internal security setting of github. Can you please push the PR after cloning the main repo only not the fork. For this create a branch of yours locally from the `next` branch and change the things needed in the branch you made and create the PR.

**Comment by opticSquid** [comment]
I'm also giving out an advisory regarding this in the github `README` other wise the PRs are not getting tracked

**Comment by opticSquid** [comment]
### UI looks great..Make something out of green too like this.. Having this color pallete
WhatsApp Image 2022-02-01 at 4 07 22 PM

**Comment by DarkFalc0n** [comment]
I got this error when trying to push to a different branch.
remote: Permission to opticSquid/hive.git denied to DarkFalc0n.
fatal: unable to access 'https://github.com/opticSquid/hive.git/': The requested URL returned error: 403

**Pull request closed without merging**
