### PR TITLE
Updated README.md file

### PR DESCRIPTION
**Pull request by raxvab**
Updated A brief summary of contributing.md file. Added the commands to run the project and a short guide of making a PR to the lower section of the Readme.md file.

fixes : #12 

Updated README.md Lower section for the contribution guidelines in a subtle manner as requested in issue#12.

I've updated the links to tutorials for installing and using git.
Apart from that, for a beginner along with the CONTRIBUTING.md I've summarized the process as well. please have a look and so notify me If I had misinterpreted the issue or if there's something more which needs to be changed.

### CODE REVIEW

**Comment by raxvab** [comment]
Hello @opticSquid Please have a look into README.md file

**Review by opticSquid — CHANGES_REQUESTED** [review]
Can we push the tech stacks and learning related things nelow project aims..

There is a little thing I missed while creating readme that now I noticed. 
In the project aims section and in the frontend sub section put backticks arround `react native` as I have done with `create-react-app`. If you can do this change too it will be really helpful.

**Comment by opticSquid** [comment]
There has been changes in the readme make sure to pull that chnages in your branch oe it will break

**Comment by raxvab** [comment]
How will I do that in github desktop can you help a bit?

**Comment by opticSquid** [comment]
go to your fork first in github it would show by how many commits your head is behind the main repo. Pull the changes to the fork. you will have all the changes updated in your main branch

**Comment by opticSquid** [comment]
https://digitaldrummerj.me/git-syncing-fork-with-original-repo/#:~:text=1%20Open%20a%20Command%20Prompt%20%28Windows%29%20or%20Terminal,repository%2C%20you%20need%20to%20push%20your%20changes.%20 Here is an article for you

**Comment by raxvab** [comment]
@opticSquid Have a look now!

**Comment by opticSquid** [comment]
Exactly mai ye to nahi keh rha tha par thik hai I will change it

**Comment by raxvab** [comment]
Ek bar discord pe converse kr lere hain fir.

**Pull request merged**
